In [2]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [9]:
A = np.random.randn(10)
A

array([ 0.06630456,  1.21120196,  0.52581238,  0.32763433,  1.3553186 ,
       -0.22326398,  1.37713853,  0.12876736, -1.04086446,  0.2587183 ])

In [10]:
B = np.random.randn(10)
B

array([ 0.5810203 ,  0.63916492, -0.72015474,  2.24354091, -0.28242455,
       -0.73670098, -0.71035162, -0.95059636, -0.58910467, -0.64569136])

In [11]:
# Binary Functions
np.add(A,B)

array([ 0.64732486,  1.85036687, -0.19434237,  2.57117524,  1.07289404,
       -0.95996496,  0.66678691, -0.821829  , -1.62996913, -0.38697306])

In [13]:
 np.maximum(A,B)

array([ 0.5810203 ,  1.21120196,  0.52581238,  2.24354091,  1.3553186 ,
       -0.22326398,  1.37713853,  0.12876736, -0.58910467,  0.2587183 ])

In [14]:
np.minimum(A,B)

array([ 0.06630456,  0.63916492, -0.72015474,  0.32763433, -0.28242455,
       -0.73670098, -0.71035162, -0.95059636, -1.04086446, -0.64569136])

In [15]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True